### ISSUE TITLE
Issue with trafficlights

### ISSUE THREAD

**Issue by kociak1984** [webdesigner97/streets#37]
I've installed your mod a week ago along with couple of others.
I've managed to make a fully automatic light system that covers about 8 crossings, but I've spotted one issue:
After placing the lights work normally: they switch colours as desired. After I leave the area, or just turn around and turn back after some time (couple of minutes) they randomly turn. They continue to work, but they look as in the attached picture.
Every unit have turned at least once, after I fix'em up they mangle again after some time.
I'm trying to hunt this in server's log, I'd post what happens if this occurs.
I'm runing v0.4.10 of Minetest.
![trafficlight-error](https://cloud.githubusercontent.com/assets/10319543/5654430/2cde675c-96c3-11e4-96b2-744bb631dbe0.jpg)

**Comment by kociak1984** [comment]
Update: sadly both server's and client's log do not show anything :/

**Comment by webdesigner97** [comment]
Which node are they attached to?

**Comment by kociak1984** [comment]
They are attached to "poles", the same mentioned in a tutorial (section: Simple setup). There is a  digiline distributor underneath each pole. I've also spotted the same problem when traffic lights are attached to fences or stone, with a digiline on the block underneath.

**Comment by webdesigner97** [comment]
These poles aren't those included in the streets modpack, are they? I'd be happy if you could test this on streets' standard poles and report the result.
Or maybe do you have a mod installed that might change the poles behaviour? They always used to work well well for me.
Unfortunately I don't have the time to do test and time-needing code fixes because of school projects and other stuff :/

**Comment by kociak1984** [comment]
Sure, I will test it on purest possible server, on fresh downloads.

**Comment by webdesigner97** [comment]
Seems to be fixed.
